<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KiTTYManager</AssemblyName>
    <ApplicationIcon>Assets\kitty-manager.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KiTTYManager.Core\KiTTYManager.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\kitty-manager.ico" />
    <Content Include="Assets\kitty-manager.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
